development:
  adapter: postgresql
  encoding: unicode
  database: invitation_dev
  host: localhost
  pool: 5
  username: maisa
  password: maisa

test:
  adapter: postgresql
  encoding: unicode
  database: invitation_test
  host: localhost
  pool: 5
  username: maisa
  password: maisa

staging:
  adapter: postgresql
  encoding: unicode
  database: invitation_prod
  host: localhost
  pool: 5
  username: postgres
  password: maisa