development:
  adapter: mysql2
  database: invitation_dev
  host: localhost
  pool: 5
  username: root
  password: root123

test:
  adapter: mysql2
  database: invitation_test
  host: localhost
  pool: 5
  username: root
  password: root123

production:
  adapter: mysql2
  database: invitation_prod
  host: localhost
  pool: 5
  username: root
  password: root123