# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
#:concurrency: 5
#:pidfile: tmp/pids/sidekiq.pid
#staging:
#  :concurrency: 10
#production:
#  :concurrency: 20
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
  - default
  - [carrierwave, 2]